---
- name: LINUX Server resource check.
  hosts: all
  vars:
 
# vmstat check
   - name: Check "vmstat -t 1 10" as SERVER RESOUCE
     shell: "vmstat 1 10 | while read line; do  echo  `date` $line  ; done"
     ignore_errors: yes
 
# Disk Size check
   - name: Check "df -h" as DISK SIZE
     shell: "df -h"
     ignore_errors: yes
 
# Memory Size check
   - name: Check "free -m" as Memory SIZE
     shell: "free -m"
     ignore_errors: yes
